apiVersion: v1
kind: Pod
metadata:
  name: health-app
  labels:
    app: health-app
spec:
  containers:
    - name: health-app
      image: health-app:@project.version@
      ports:
        - containerPort: 8080
